---
services:
  target:
    build: .
    command: test
    entrypoint:
      - bundle
      - exec
      - kitchen
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-us-east-1}
    volumes:
      - .:/target
    working_dir: /target
version: '3'
