---
driver:
  name: ec2

platforms:
  - driver:
      image_id: ami-03a3accd0c3483a79
    name: ubuntu-16.04

provisioner:
  hosts: all
  idempotency_test: true
  name: ansible_playbook
  require_chef_for_busser: false
  require_ruby_for_busser: false

suites:
  - name: default

verifier:
  name: inspec
