---

- name: Create bash initialization files
  file:
    access_time: preserve
    modification_time: preserve
    path: '{{ item }}'
    state: touch
  with_items:
    - '{{ ansible_env.HOME }}/.bashrc'
    - '{{ ansible_env.HOME }}/.bash_profile'

- name: Uninstall unattended-upgrades
  apt:
    name: unattended-upgrades
    state: absent
  become: true

- name: Install required packages
  apt:
    name:
      - g++
      - git
      - unzip
    state: present
    update_cache: false
  become: true

- name: Disable apt-daily.timer
  systemd:
    enabled: false
    name: apt-daily.timer
    state: stopped
  become: true

- name: Download and install Packer
  unarchive:
    creates: /usr/local/bin/packer
    dest: /usr/local/bin
    remote_src: true
    src: https://releases.hashicorp.com/packer/1.4.2/packer_1.4.2_linux_amd64.zip
  become: true
