---

- name: Create bash initialization files
  file:
    path: '{{ item }}'
    state: touch
  with_items:
    - '{{ ansible_env.HOME }}/.bashrc'
    - '{{ ansible_env.HOME }}/.bash_profile'

- name: Install required packages
  apt:
    name:
      - g++
      - git
      - unzip
    state: present
    update_cache: false
  become: true

- name: Disable apt-daily.service and apt-daily.timer
  systemd:
    enabled: false
    name: '{{ item }}'
    state: stopped
  become: true
  with_items:
    - apt-daily.service
    - apt-daily.timer

- name: Download and install Packer
  unarchive:
    dest: /usr/local/bin
    remote_src: true
    src: https://releases.hashicorp.com/packer/1.4.2/packer_1.4.2_linux_amd64.zip
  become: true
